### ISSUE TITLE
change to actually use K6_ES_ENABLE_SNIFFER

### ISSUE THREAD

**Issue by timterrill** [BarthV/xk6-es#2]
Hello,

I built a new k6 executable using your extension, but when attempting to connect to ES, it would fail to connect.

After looking around a bit, i eventually figured out why.  My cluster needs K6_ES_ENABLE_SNIFFER=false, but in the code in "internal/config.go" it has it always set to "true":

```
		case "K6_ES_ENABLE_SNIFFER":
			cfg.SnifferEnabled = true

```

I made the following change, and it builds and runs fine now :)

```
		case "K6_ES_ENABLE_SNIFFER":
			var err error
			cfg.SnifferEnabled, err = strconv.ParseBool(v)
			if err != nil {
				return cfg, fmt.Errorf("error parsing environment variable 'K6_ES_ENABLE_SNIFFER': %w", err)
			}

```

I attempted to push my change, but it didn't let me...

I'll use my local mod until the time you are able to make the change in the code.

I just started getting data into ES, so now I have to play with visualizing my k6 data...

Thanks!
Tim

**Comment by BarthV** [comment]
https://github.com/BarthV/xk6-es/releases/tag/v0.0.3

with your proposed update :
https://github.com/BarthV/xk6-es/commit/e4e9507461df2bb518dcf9ebb3fb79a70bd80bbf

thanks

**Comment by timterrill** [comment]
awesome!  I'll give it a try today :)

**Comment by timterrill** [comment]
Thank you, it works!
